# Generated by Django 4.0.2 on 2022-02-03 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_event_event_status_alter_event_support_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractstatus',
            name='signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.contractstatus'),
        ),
    ]
